version: "3"

services:
  front:
    image: hello-docker-react:latest
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
